### ISSUE TITLE
Seg fault on Swift 2.2

### ISSUE THREAD

**Issue by dart-h-vader** [romainmenke/ScrollViewImager#1]
Trying to run the project in a playground causes it to segfault. 

I believe the issue is with the nested functions of the library (makeScreenshots and makeScreenshotRow methods)

**Comment by romainmenke** [comment]
This has been resolved by removing the Mixin Pattern and implementing a regular Extension

**Comment by dart-h-vader** [comment]
Wow! that was quick and a huge thank you!
